### ISSUE TITLE
Hat selector 2.0

### ISSUE THREAD

**Issue by Blackhawk95** [dabjulmaros/dabjulmaros.github.io#3]
A friend of mine introduced me to this webapp. It does exactly what it says. 

But I wish there was a dropdown for hats. That will prevent people from misuing this app for nefarious purposes.

Its just a food for thought.
Ofcourse your code monkeys are allowed to reject the idea if they feels so.

**Comment by dabjulmaros** [comment]
hello,
thank you for you idea. Here at dabjulmaros inc trust corporation we are always open for new ideas, that may help and improve our software for our valued users. In regard to your suggestion we really apreciate it. Our code monkeys have looked at it, and plan to implement it:
never.
thank you again,
Dabjulmaros ceo,cto,intern

**Comment by dabjulmaros** [comment]
Nah but for real, the main goal was to add the silly top hat to the monocle emoji. Turns out there seems to be a lot of potential for funny combinations, and I wouldnt want limit any possible potential.
Trust me, i have seen some cursed stuff made using it. 
I do want to add a quick selector for the available hats, and possibly some "recent faces", but not limit it.
P.S bombard danny with hatted emojis for making issues, he hates them 😂.
